services:
  mysql:
    image: mysql:8.0
    container_name: coffee-crm-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - coffee_crm_data:/var/lib/mysql

volumes:
  coffee_crm_data: